### ISSUE TITLE
Error importing NES

### ISSUE THREAD

**Issue by cognitivegears** [mrsonicblue/peek-scan#1]
When importing from NES, I get the following error:

Core: NES (49 of 60)... processed 954 of 1786 roms     Unhandled exception. System.IO.InvalidDataException: Central Directory corrupt.
 ---> System.IO.IOException: Invalid argument
   at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at Peek.Scan.Scanner.GetHash(FileInfo file, Int32 headerSize) in /project/Scanner.cs:line 101
   at Peek.Scan.Scanner.Run() in /project/Scanner.cs:line 199
   at Peek.Scan.Program.Main(String[] args) in /project/Program.cs:line 27
Aborted

**Comment by cognitivegears** [comment]
Validated that with the most recent release this issue is corrected. Closing the issue.
